### ISSUE TITLE
error: Too many concurrent aggregations

### ISSUE THREAD

**Issue by abczefg** [12rambau/restoration_planning_module#102]
I tried to run another recipe with lots of constraints and it returns this error: Too many concurrent aggregations
Not sure if it is related to the instance I was using (t2)..

[recipe_2021-12-20-2.txt](https://github.com/12rambau/restoration_planning_module/files/7742383/recipe_2021-12-20-2.txt)

**Comment by abczefg** [comment]
The above mentioned error remains when I switched the instance to m2.

**Comment by jdilger** [comment]
Hi @abczefg I'll take a look into this today. Too many concurrent aggregations is going to be an EE error, so changing the instance size would not help in this case.

**Comment by jdilger** [comment]
Also, where did this error occur? computing the results map or computing the dashboard?

**Comment by abczefg** [comment]
Hi @jdilger this error occurred at the compute dashboard step

**Comment by jdilger** [comment]
@abczefg just to follow up, I was able to recreate the error. The timeout is likly GEE but since there are land cover constraints it could be related to #101
