### ISSUE TITLE
Difference between questionaire_io.constraints and default_questionaire_io.constraints formatting

### ISSUE THREAD

**Issue by jdilger** [12rambau/restoration_planning_module#12]
What is going to be the final formatting for when we get the constraints from the questionaire_io? Calling it currently yields a string such as below:

{"Bare land": true, "Shrub land": true, "Agricultural land": false, "Annual rainfall": 5, "Population": -1, "Elevation": -1, "Slope": -1, "Tree cover": -1, "Protected area": -1, "Opportunity cost": -1}

But if we use the default questionnaire (io.questionnaire_io.default_questionnaire_io.constraints ) we get: 
{"Bare land": [true, false, 51], "Shrub land": [false, false, 91], "Agricultural land": [false, true, 12], "Annual rainfall": [true, true, 81], "Population": [true, false, 35], "Elevation": [false, false, 5], "Slope": [true, false, 74], "Tree cover": [false, true, 72], "Protected area": [true, true, 15], "Opportunity cost": [true, true, 30]}

The formatting of the default is easier to use, but I do have it working using the current output.

**Comment by 12rambau** [comment]
So as said in our last call, @yfinegold asked me to change the inputs to make more sense to the end user. the list is available in this issue : https://github.com/12rambau/restoration_planning_module/issues/7 

From what I understand I agree with her that lots of the constraints are not really compatible with a "less than"/"more than" + value switch.

Instead what I've done is 
 - `-1` => deactivated for all 
 - for the boolean False (0) or True (1) (I'm sure you've seen this one coming)
 - for the dropdown it's a fix value and I think you could take a range around the value to make sens
 -  treecover is the last Slider and I would say it's a "more than"

So unfortunately for you, I would like the `questionnaire_io`formatting to become the one. 

If it leads to technical issue, let me know and we'll schedule a meeting this week to converge to something that fit your needs better.

**Comment by jdilger** [comment]
OK, that's not a problem.  I have it set up to use that formatting already.

**Comment by jdilger** [comment]
@12rambau related to this, which is the io that is updated when values are selected?

I've been calling rp_questionaire_io.constraints, but the values do not change when items are selected/deselected in the questionnaire.

**Comment by 12rambau** [comment]
I don't manage to reproduce your error 
Here I will modify the criterias and the `constraints` member is actually changing
 
https://user-images.githubusercontent.com/12596392/111512205-ca3b9280-874f-11eb-9efc-6fda4e3fd8f3.mov
