### ISSUE TITLE
create  a quintile maker

### ISSUE THREAD

**Issue by 12rambau** [12rambau/restoration_planning_module#17]
We decided to prebuild quintile layers to improve computation speed. i agree it makes lot of sens. But we then need to provide to people who would be interested in using their own local layer to produce quinitle layers themselve.

**Comment by 12rambau** [comment]
@jdilger Could you share with me the script that you used to create these quintile layers so that I can apply it in an extra Tile ?

**Comment by jdilger** [comment]
@12rambau The python versions are in [functions.py](https://github.com/12rambau/restoration_planning_module/blob/abaa7cc01216469b58370abcd68c65855dad84ef/component/scripts/functions.py#L100) (incorrectly named at the moment...) How do you envision the tile? I can move the functions into a more usable script if you'd like. I do have a javascript version of the [script ](https://code.earthengine.google.com/8c081d5ffcdcdf9f14a03754dc4e7563) ready to go though.

**Comment by 12rambau** [comment]
So if you open the ui, you'll see a new tile after the about section. 

I would like to wire it on the btn click here : https://github.com/12rambau/restoration_planning_module/blob/856f6b23535f3f9fd5e4db42c6e3e28c73a5411c/component/tile/quintile_tile.py#L46

In a second step I need to export it as an asset and give the user some feedback.

**Comment by jdilger** [comment]
Do we still plan on implementing this? Since we're doing quintiles on the fly I am not sure we need to.

**Comment by 12rambau** [comment]
no we don't 😄
