### ISSUE TITLE
how to test layers when user provide custom asset

### ISSUE THREAD

**Issue by 12rambau** [12rambau/restoration_planning_module#19]
In the dialog I would like to test if the layer is compatible with rest of the app

I assume that once this issue #17 will be solved I will have everything I need to test it but still, I don't know yet what to test.

**Comment by jdilger** [comment]
Testing could be somewhat difficult... maybe we do a min/max reducer to check that it's within the valid range (1-5) and check that they're also integers.

**Comment by 12rambau** [comment]
> maybe we do a min/max reducer to check that it's within the valid range (1-5) and check that they're also integers.

that's typically what i would like to test

**Comment by 12rambau** [comment]
Now that we do the normalization on the fly i don't need to test anything, I just import the image and compute the min and max for visualization. If it fails, I fallback to the default one (without catching the error because there are too many possible errors)
