### ISSUE TITLE
any specific reason why all your function are wrapped in a class ? 

### ISSUE THREAD

**Issue by 12rambau** [12rambau/restoration_planning_module#21]
@jdilger, I was trying to find my way in here:  https://github.com/12rambau/restoration_planning_module/blob/master/component/scripts/functions.py

And I was wondering, Is there a specific reason for using an object ? 

lots of them seems static to me so, but maybe I'm not seeing something more obvious

**Comment by jdilger** [comment]
@12rambau When I started it I feel like I had a reason, but I can't think of why it needs to be in a class.
