### ISSUE TITLE
questionnaire changes

### ISSUE THREAD

**Issue by yfinegold** [12rambau/restoration_planning_module#22]
combine tabs 1 and 2 by adding the content of tab 2 under the contents of tab 1. 
Restoration potential and land use is a type of constraint so it would be more logical to group thoses together.

It would be more intuitive to break down the choices in the criteria into different options as such: 
Land use constraints: land use classes (bare, shrub, cropland)
Biophysical constraints: rainfall, elevation, slope
Socio-economic constraints: protected areas, population, opportunity cost
Tree cover constraints within land cover classes: (% tree cover in ag, rangeland, grassland, settlements) - that's tab2

For the land use constraints lets take out the switch button. Once a class is select then it a constraint, the user should need to switch another button. 

Let me know if anything is unclear!

**Comment by yfinegold** [comment]
Let's get rid of tab 3. Just totally delete that.

**Comment by yfinegold** [comment]
Tab 4
Could you change the priorities to match with the subthemes? 
That would be: 
local livelihoods
wood production
non-timber tree benefits
water quality

**Comment by 12rambau** [comment]
sum up : 
- [ ] remove tab 3 
- [ ] change priorities name in tab 4 
- [ ] change tab 2 

for the changes in tab 2: 
- the switch is compulsory to not alter the rest of the criterias functionning. But I will make the switch defaulting to true and readonly so no action will be needed from the user. 
- for the break you mean adding header in the dropdown list or break it in separated dropdown ?
