### ISSUE TITLE
Guido's forest fragmentation layer

### ISSUE THREAD

**Issue by jdilger** [12rambau/restoration_planning_module#23]
This is more of a gee issue... but I am having trouble getting the forest fragmentation layer into gee. The fragmentation layers are in a projection (EPSG:54052) that isn't supported by GEE. I have tried using gdalwarp to reproject them to EPSG:4326 and EPSG:3857 
 which completes successfully, but ends up highly distorted. 

@yfinegold @12rambau have either of you worked with this projection or the forest fragmentation layers before? Any advice would be helpful! They're rather large too, so the time to fail testing is quite long... 

GDAL Info for context:
>gdalinfo fm30_fad_31.tif
Driver: GTiff/GeoTIFF
Files: fm30_fad_31.tif
Size is 400751, 147307
Coordinate System is:
PROJCS["World_Goode_Homolosine_Land",
    GEOGCS["GCS_WGS_1984",
        DATUM["D_WGS_1984",
            SPHEROID["WGS_1984",6378137.0,298.257223563]],
        PRIMEM["Greenwich",0.0],
        UNIT["Degree",0.017453292519943295]],
    PROJECTION["Goode_Homolosine"],
    PARAMETER["False_Easting",0.0],
    PARAMETER["False_Northing",0.0],
    PARAMETER["Central_Meridian",0.0],
    PARAMETER["Option",1.0],
    UNIT["Meter",1.0]]
Origin = (-20037507.067161846905947,8190730.585661163553596)
Pixel Size = (100.000000000000000,-100.000000000000000)
Metadata:
  AREA_OR_POINT=Area
  TIFFTAG_DATETIME=2019:09:30 10:24:41
  TIFFTAG_DOCUMENTNAME=fm30_fad_31.tif
  TIFFTAG_IMAGEDESCRIPTION=GTB_FOS, https://forest.jrc.ec.europa.eu/en/activities/lpa/gtb/
  TIFFTAG_RESOLUTIONUNIT=2 (pixels/inch)
  TIFFTAG_SOFTWARE=IDL 8.7.0, Harris Geospatial Solutions, Inc.
  TIFFTAG_XRESOLUTION=100
  TIFFTAG_YRESOLUTION=100
Image Structure Metadata:
  COMPRESSION=LZW
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  (-20037507.067, 8190730.586)
Lower Left  (-20037507.067,-6539969.414)
Upper Right (20037592.933, 8190730.586)
Lower Right (20037592.933,-6539969.414)
Center      (      42.933,  825380.586) (  0d 0' 1.40"E,  7d24'52.27"N)
Band 1 Block=400751x1 Type=Byte, ColorInterp=Palette
  Color Table (RGB with 256 entries)
    0: 213,48,38,255
    1: 213,48,38,255
     ....

**Comment by 12rambau** [comment]
I have never seen this projection before

**Comment by yfinegold** [comment]
Oh yikes.. I will give it a look and can get in touch with colleagues at JRC if the issue persists

**Comment by jdilger** [comment]
@yfinegold thanks let me know if you figure anything out. I tried projecting to a random UTM but ended up with a warp that looked like a panda...

**Comment by jdilger** [comment]
Alright, it looks like twitter came through!  The correct gdal command to project he fragmentation layer was:

gdalwarp s_srs "+proj=igh +datum=WGS84 +x_0=0.0 +y_0=0.0 +lon_0=0dE +no_defs" -t_srs EPSG:4326 -overwrite -co "COMPRESS=DEFLATE" fm30_fad_31.tif fm30_fad_31_proj.tif

Looks like some of the confusion is that EPSG:54052 isn't an EPSG code, it's an ESRI code.
