### ISSUE TITLE
how should I display the risks layer in the dashboard ? 

### ISSUE THREAD

**Issue by 12rambau** [12rambau/restoration_planning_module#24]
@jdilger in the wireframe, the risks are quoted in the "costs" txt : 

"Note: Estimates on the probability of natural regeneration success is included in the "Risks" category." but this theme is not displayed on the dashboard. Should i use the same display as benefits or constraints ?

**Comment by jdilger** [comment]
@12rambau we talked about having them shown as single values (specifically for anything that is a national level product).  Ideally, there would be a separate small section for risks.

**Comment by 12rambau** [comment]
Ok i'll create a dashboard tile that kinda look like the one you've designed and use a json to populate itself (I'll give you the format in the top of the tile file)
