### ISSUE TITLE
Question about planned language selection with relation to constraints

### ISSUE THREAD

**Issue by jdilger** [12rambau/restoration_planning_module#26]
@12rambau I know we are planning on being able to load in different languages for the app.. when this is implemented will this change the names associated with all the GUI parameters?

Right now I find the proper constraints based on matching them to the layer name or GUI name for constraints that are not individual layers(eg. bare land cover).  If we are anticipating these names to be variable based on the language I could use some help figuring out a better way to approach this issue.

**Comment by 12rambau** [comment]
So in dropdown and everything I can use a different text than the name. It will be very little work for me. 
My suggestion keep it as it is for the moment and use the english names. 

When We'll move to translation, I'll continue using these keys in the json but I will display something else in the corresponding dropdowns

**Comment by jdilger** [comment]
Awesome, thanks Pierrick
