### ISSUE TITLE
Exporting stats for dashboard

### ISSUE THREAD

**Issue by jdilger** [12rambau/restoration_planning_module#27]
@12rambau can you point me to an example of how we want to export the results to populate the dashboard? I am thinking as a CSV should be fine.

**Comment by 12rambau** [comment]
Anything you can produce, I'll manage to read it. I'm agnostic at the moment and I think it's more complicated on your side

**Comment by jdilger** [comment]
I am thinking geojson now. When you export a dictionary to csv they don't keep quotations for some reason...  We can adjust later if a csv is better for whatever reason. 

New issue is it takes fairly long for the stats to export. The couple of tests I've run clock in at 10 - 15m. Unfortunately, I think this is due to the AOI shape rather than the area. When I test using a bounding box it exports in a few minutes. I still need to confirm this though...

**Comment by jdilger** [comment]
https://github.com/openforis/gfc_wrapper_python/blob/dcc4606fa9594ba575866e2b89eb2c87789c24f7/utils/gdrive.py#L16

Is ee.Credentials a service account thing? I am wanting to export the dashboard results to the users drive then read them. But I get an error ee.Credentials doesn't exist

**Comment by 12rambau** [comment]
no normally it should work with a regular GEE account. Did you linked your SEPAL account to Google using èarthengine authenticate`or by linking it using the [SEPAL linking process](https://docs.sepal.io/en/latest/setup/gee.html#connection-between-gee-and-sepal) ?
