### ISSUE TITLE
limit the selectable areas in the aoi_selector

### ISSUE THREAD

**Issue by 12rambau** [12rambau/restoration_planning_module#28]
1. Jeff: The geographical scope of the tool should be limited to land that meets these four criteria ("restorable land"): 
1. Located in LMICs 
2. Trees can exist on it (per Bastin et al. 2019) 
3. Trees do not currently exist on it (suggestion: use 2019 Copernicus 100m land-cover data)
4. Not urban (suggestion: use 2019 Copernicus 100m land-cover data). 
Bins, etc. should be defined using only this land. For (iii), we will need to decide which Copernicus land-cover classes to consider to be "tree cover." I think we're doing all this, but let's confirm. 
John: I've drafted this layer using all the forest type layers in GEE 
script: https://code.earthengine.google.com/39f660dc8bd71b5d30a01c0ef6c63ab1

**Comment by jdilger** [comment]
I've made two layers related to this:
a. Trees can exist on it, where Trees do not currently exist on it, and is not urban.(layer name: Current forest or ubran landscape)
b. Trees do not currently exist on it, and they're less than the current tree cover fraction.(layer name: Current tree cover less than potential)

Right now they're added to the constraints list/ questionnaire, but it sounds like they should be nonoptional constraints in an either/both situation. @12rambau what do you think would be the best way to add this?

For 2.Located in LMIC, are we going to impose this at the AOI selection?

**Comment by 12rambau** [comment]
I think we should hardcode them into the gee side. They should not be constraints that people could select or deselct at will
