### ISSUE TITLE
How to use the dropdowns from Jeff ?

### ISSUE THREAD

**Issue by 12rambau** [12rambau/restoration_planning_module#30]
@jdilger , I read the proposed values for the dropdown criterias that Jeff send us and I don't really understand how to use them as they are not 3 offset but 2 ....

I didn't have the time to check the code on your side but I don't know how you are using these values, is it possible to use what Jeff proposed ?

**Comment by jdilger** [comment]
@12rambau Jeff wants to be able to do both greater than and less than operators on dropdown constraints. What do you think the best method would be to add this in? 

Could I add it as a column in the layer list?
