### ISSUE TITLE
produce a layer to display and a dashboard 

### ISSUE THREAD

**Issue by 12rambau** [12rambau/restoration_planning_module#4]
Once you get the input of the algorithm we need to create a kayer that will be display on the map.
I suggets to export this layer to the user asset (or at least give them this oportunity).

The algorithm is supposed to create a dashboard as well. The markdown sepal_ui is indicated to create smooth and nice display of all our information.

all the function have a default implementation [here](https://github.com/12rambau/restoration_planning_module/blob/master/scripts/compute.py) and are used [here](https://github.com/12rambau/restoration_planning_module/blob/master/compute_ui.ipynb)

**Comment by 12rambau** [comment]
@jdilger, based on what you displayed with karis during the last meeting, I was thinking of using a lib that transform html into pdf to generate the dashboard files. 
my favorite one is https://weasyprint.org IDo you have anything else in mind ?

**Comment by jdilger** [comment]
@12rambau that looks good to me. I haven't had a reason to transform anything into a pdf so I will default to your knowledge!
