### ISSUE TITLE
custom AOI are not recognize as LMIC country 

### ISSUE THREAD

**Issue by 12rambau** [12rambau/restoration_planning_module#44]
One of our collegue have tried to use a custom asset that have been analysed as not fully qualified after the LMIC test:
https://github.com/12rambau/restoration_planning_module/blob/01e03c772d29fd900e4d8da3977e01c0a9131761/component/tile/custom_aoi_tile.py#L15

this should be the case. 

I need to find a faster way to this test or remove it entirely.

**data to reproduce**
users/nephentes77/nigeria/AOIdissolved

**Comment by jdilger** [comment]
Any update on this @12rambau ? I am testing out a rasterized solution that I think will work well.

**Comment by 12rambau** [comment]
I didn't work on this, I was working on naming sub AOIs, please be my guest

**Comment by 12rambau** [comment]
Our main gaol will be to make it work by tomorrow morning to have a functional app before the focus group with columbia. If you don't find an faster solution, I'll go with an ugly but very efficient if statement on the admin member of the aoi_model. 

I'll have the surprise tomorrow morning I guess ;-)

**Comment by jdilger** [comment]
Alright, it should be working now. I wanted to get rid of the getInfo(), but it's ok. I think it's a much faster solution.  

This uses a raster of the LMIC countries that's been buffered, paints the input geometry, adds them together, and then computes a bitwiseAnd reducer. The test is if the reducer returns 2 which is full coverage of the input raster and the LMCI raster. It returns 1 for partial coverage and 0 for none -but we don't test for that. 

https://github.com/12rambau/restoration_planning_module/commit/da799f2d8afbc6aef00f84701ab179c7edb50f9e

**Comment by 12rambau** [comment]
almost there, I tested it over huge areas Indonesia and it doesn't work (it resets the aoi selection)

**Comment by 12rambau** [comment]
I added a custom test over the administrative layer. There will still be a problem with islands but at least now it will be handled if people simply use admin definitions (90% of our users according to Yelena)

**Comment by jdilger** [comment]
I wonder if all benefit layers even cover small islands like those.

**Comment by 12rambau** [comment]
I'm not sure but for all the countries that includes small island within their borders it won't refuse to compute at least
