### ISSUE TITLE
upload custom AOI for dashboard comparsion

### ISSUE THREAD

**Issue by yfinegold** [12rambau/restoration_planning_module#46]
Would it be possible to upload a custom AOI for the sub-areas in the dashboard analysis? This would be useful for comparing actual potential project sites, for example comparing 2 districts where forest restoration is being considered.

**Comment by 12rambau** [comment]
this is formally incompatible with what we currently have. but I'll try to find a workaround, I see that it would be an extremely useful feature.

**Comment by 12rambau** [comment]
but now it's done : https://github.com/12rambau/restoration_planning_module/commit/ad936c22330b7c5e82c5ccc4c96f2a538d04ce7f
