### ISSUE TITLE
force cast all alyer to ee.Image

### ISSUE THREAD

**Issue by 12rambau** [12rambau/restoration_planning_module#59]
I wanted to demonstrate the layer customization and I think it would be better if every layer have an homogeneous type (`ee.image`). Would it be possible to rasterize the remaining `featureCollections` and put them in the same bucket ?

**Comment by jdilger** [comment]
They look good to me. Exporting now and will push the changes to the layer list once finished. I think I will move over all the files to a new project specifically for se.plan at some point in the near future as well.
