### ISSUE TITLE
Cannot recreate baseline restorable mask and restoration potential issues

### ISSUE THREAD

**Issue by jdilger** [12rambau/restoration_planning_module#65]
I have been unable to recreate the baseline restorable area mask, and so I suggest we remake the layer and replace it. 

Additionally, the restoration potential image we've been using appears to have been modified at some point so we should switch to Yelena's copy or make a new copy from the webapp. I must have exported it at some point to scale it between 0-1 and also lowered the resolution which is no good.

@12rambau I have a private repo where I have stored one-off processing scripts for the benefits/costs/constraints do you think we should have a shared repo to store these in for long term maintainability? And if so it'd be nice to think of a way we can have them all either in a JS repo or here on github.

- [x] copy over unmodified restoration potential image
- [x] create new base restorable land

**Comment by 12rambau** [comment]
So it seems that the issue is solved, would you mind adding the script you used to the `utils/code` folder ?
