### ISSUE TITLE
explain what percentage is in the dashboard

### ISSUE THREAD

**Issue by 12rambau** [12rambau/restoration_planning_module#89]
Q: What does the percentage mean in the dashboard?
(In this case I only put one constraint (populaiton density, unit: Total number of people per square kilometer)

What does 0.0% mean? Did I (not) assign it or it is calculated by se.plan?
<img width="278" alt="Capture d’écran 2021-12-03 à 09 47 11" src="https://user-images.githubusercontent.com/12596392/144573018-7d3cdf63-522d-484d-b835-35cadc2206af.png">

**Comment by jdilger** [comment]
It's the percent of the area constrained within a region. 0% would be either it was not selected as a constraint or it was selected but did not constrain anything within the region. 

It's a little confusing admittedly. We could probably change it something like "Not selected" to make it more clear.

**Comment by 12rambau** [comment]
That's what I answered to him during the call (sorry I was just copy/pasting questions from a word document. 

I think I can mix the different information available when I build the dashboard to only display the one that are activated.
