### ISSUE TITLE
se.plan failing to load

### ISSUE THREAD

**Issue by jdilger** [12rambau/restoration_planning_module#91]
One of our partners in Nepal is having trouble getting se.plan to load in SEPAL, @12rambau do you have any insights on what could be happening? Basically, after he launches se.plan it will spin for a few minutes, then turn all black, but never finish loading the UI. 

I did a call with him to verify that it was not loading. The steps we did to load the app were:
1. Start new T2 instance
2. Launch se.plan from app's 
3. Wait (~2-3min until the spinning stopped, then 5-7 min black screen)

**Comment by 12rambau** [comment]
very strange indeed. 

Could try with a bigger instance for the sake of verification ? 
Have you experienced the same on your SEPAL account ?

**Comment by jdilger** [comment]
I think trying a bigger instance is a logical next step. I need to find who hands out the SEPAL money though as they're only getting a couple of dollars a month, and I don't want to use up all their money testing :).

I haven't experienced that with my account no. At time's it will never stop spinning if I tab away, but whenever I sit and wait with it open it loads.

**Comment by 12rambau** [comment]
If your user have used SEPAL lets say mid-may last year, I did a very bad implementation in SEPAL apps. Me and my boss were not patient enough and we wanted to bypass the rebuild of the platform and force install the latest version of sepal_ui locally every time someone opens a module. 

that ended-up with every user having local installation of deprecated libs (sepal_ui, tensorflow,...) hidden in their .local folder. using the terminal you can simply drop it and see if it changes anything.

**Comment by abczefg** [comment]
It also happen to me (in China) many times. I saw in the browser's console that there are a lot of error messages, which is usually the case before I could launch it. I can share my screen to show you if you're interested to see the errors. Zhuo

**Comment by 12rambau** [comment]
closed in https://github.com/openforis/sepal/issues/150
