### ISSUE TITLE
use the legend label from ESA CCI

### ISSUE THREAD

**Issue by 12rambau** [12rambau/restoration_planning_module#92]
@yfinegold told me that the names are not corresponding from ESA CCI to conttraint names: 

https://github.com/12rambau/restoration_planning_module/blob/4f3456cc00ebe2261c5ee0dba09592a9a6bdfce5/component/parameter/gui_params.py#L2

**Comment by jdilger** [comment]
I could only find 2 differences between shrubs and agriculture. The agriculture name is a bit long, would this be an issue? should it be truncated?

Copernicus Global Land Service: Land Cover 100m: version 3 Globe 2015-2019: Product User Manual with class typology: https://zenodo.org/record/3938963

landcover_default_cat = {
    "**Shrubs**": 20,
    "Herbaceous vegetation": 30,
    "**Cultivated and managed
vegetation/agriculture
(cropland)**
": 40,
    "Urban / built up": 50,
    "Bare / sparse vegetation": 60,
    "Snow and ice": 70,
    "Herbaceous wetland": 90,
    "Moss and lichen": 100,
}

**Comment by 12rambau** [comment]
@yfinegold ?

**Comment by 12rambau** [comment]
as title are always displayed as a 1 liner so it's ok 

![Capture d’écran 2022-01-21 à 18 29 19](https://user-images.githubusercontent.com/12596392/150572853-6f1d342b-e9b4-4627-b3ea-f052f7077084.png)
