### ISSUE TITLE
Saving recipe - Object of type Image is not JSON serializable

### ISSUE THREAD

**Issue by jdilger** [12rambau/restoration_planning_module#93]
While doing some iterative constraint testing I ran into the error "Object of type Image is not JSON serializable". @12rambau have you had this happen before? Just guessing here, but it reads like an ee.Image made its way into the recipe. I was using one custom constraint asset but deleting it, and switching to the default image produced the same error when trying to save. 

![image](https://user-images.githubusercontent.com/32108051/144683661-1b15ca32-7d5d-40a4-915b-611112ee515b.png)

**Comment by 12rambau** [comment]
I never ran into this issue before but that's weird, if you run it in dev mode, you'll see a more detailed version of the error (including the lines involved)

**Comment by jdilger** [comment]
Ah I think I know where something is going wrong. Looks like it partially saved the json and errored out right after an "ee_image" dict key. That key is used to hold ee.Image objects so it makes sense.

**Comment by 12rambau** [comment]
nice catch !

**Comment by jdilger** [comment]
Thanks! I think the typo/old key was the only issue here.
