### ISSUE TITLE
error message "Number.add: Parameter 'left' is required" after clicking compute restoration map

### ISSUE THREAD

**Issue by 12rambau** [12rambau/restoration_planning_module#94]
transferring from sepal-doc issues https://github.com/openforis/sepal-doc/issues/100 

from @abczefg 
> I built up this recipe (attached), and at the result map panel, after clicking "compute restoration map", I got this error message: Number.add: Parameter 'left' is required.
Then I tried to change the AoI and constraints, but still got the same error.

<img width="641" alt="Screenshot 2021-12-06 at 20 09 07" src="https://user-images.githubusercontent.com/71498789/144860497-7c8e29c2-3153-4c50-b4bd-9e28e054bb7c.png">

[recipe_2021-12-06-test.txt](https://github.com/openforis/sepal-doc/files/7661220/recipe_2021-12-06-test.txt)

**Comment by abczefg** [comment]
this is solved
10 Dec 2021
